# Generated by Django 5.2.3 on 2025-07-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_proveedor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='imagen',
        ),
    ]
