# Generated by Django 5.2.3 on 2025-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0003_remove_proveedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
    ]
